[auth.external.google]
enabled = true
client_id = 433157555104-0us9fh3eggq51uaf3g7leitnht7bpfct.apps.googleusercontent.com
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false